// Source: Mondieki/kenya-counties-subcounties (MIT), IEBC-based sub-county/
// constituency boundaries, cross-checked against IEBC's own constituency list.
// Kisii's entry was empty in that dataset and has been filled in manually from
// IEBC's published constituency list for Kisii County.
export const KENYA_COUNTY_SUBCOUNTIES: Record<string, string[]> = {
  "Baringo": ["Baringo Central", "Baringo North", "Baringo South", "Eldama Ravine", "Mogotio", "Tiaty"],
  "Bomet": ["Bomet Central", "Bomet East", "Chepalungu", "Konoin", "Sotik"],
  "Bungoma": ["Bumula", "Kabuchai", "Kanduyi", "Kimilil", "Mt Elgon", "Sirisia", "Tongaren", "Webuye East", "Webuye West"],
  "Busia": ["Budalangi", "Butula", "Funyula", "Nambele", "Teso North", "Teso South"],
  "Elgeyo-Marakwet": ["Keiyo North", "Keiyo South", "Marakwet East", "Marakwet West"],
  "Embu": ["Manyatta", "Mbeere North", "Mbeere South", "Runyenjes"],
  "Garissa": ["Daadab", "Fafi", "Garissa", "Hulugho", "Ijara", "Lagdera Balambala"],
  "Homa Bay": ["Homabay Town", "Kabondo", "Karachwonyo", "Kasipul", "Mbita", "Ndhiwa", "Rangwe", "Suba"],
  "Isiolo": ["Central", "Garba Tula", "Kina", "Merit", "Oldonyiro", "Sericho"],
  "Kajiado": ["Isinya.", "Kajiado Central.", "Kajiado North.", "Loitokitok.", "Mashuuru."],
  "Kakamega": ["Butere", "Kakamega Central", "Kakamega East", "Kakamega North", "Kakamega South", "Khwisero", "Lugari", "Lukuyani", "Lurambi", "Matete", "Mumias", "Mutungu", "Navakholo"],
  "Kericho": ["Ainamoi", "Belgut", "Bureti", "Kipkelion East", "Kipkelion West", "Soin Sigowet"],
  "Kiambu": ["Gatundu North", "Gatundu South", "Githunguri", "Juja", "Kabete", "Kiambaa", "Kiambu", "Kikuyu", "Lari", "Limuru", "Ruiru", "Thika Town"],
  "Kilifi": ["Genzw", "Kaloleni", "Kilifi North", "Kilifi South", "Magarini", "Malindi", "Rabai"],
  "Kirinyaga": ["Kirinyaga Central", "Kirinyaga East", "Kirinyaga West", "Mwea East", "Mwea West"],
  "Kisii": ["Bobasi", "Bomachoge Borabu", "Bomachoge Chache", "Bonchari", "Kitutu Chache North", "Kitutu Chache South", "Nyaribari Chache", "Nyaribari Masaba", "South Mugirango"],
  "Kisumu": ["Kisumu Central", "Kisumu East", "Kisumu West", "Mohoroni", "Nyakach", "Nyando", "Seme"],
  "Kitui": ["Ikutha", "Katulani", "Kisasi", "Kitui Central", "Kitui West", "Lower Yatta", "Matiyani", "Migwani", "Mutitu", "Mutomo", "Muumonikyusu", "Mwingi Central", "Mwingi East", "Nzambani", "Tseikuru"],
  "Kwale": ["Kinango", "Lungalunga", "Msambweni", "Mutuga"],
  "Laikipia": ["Laikipia Central", "Laikipia East", "Laikipia North", "Laikipia West", "Nyahururu"],
  "Lamu": ["Lamu East", "Lamu West"],
  "Machakos": ["Kathiani", "Machakos Town", "Masinga", "Matungulu", "Mavoko", "Mwala", "Yatta"],
  "Makueni": ["Kaiti", "Kibwei West", "Kibwezi East", "Kilome", "Makueni", "Mbooni"],
  "Mandera": ["Banissa", "Lafey", "Mandera East", "Mandera North", "Mandera South", "Mandera West"],
  "Marsabit": ["Laisamis", "Moyale", "North Hor", "Saku"],
  "Meru": ["Buuri", "Igembe Central", "Igembe North", "Igembe South", "Imenti Central", "Imenti North", "Imenti South", "Tigania East", "Tigania West"],
  "Migori": ["Awendo", "Kuria East", "Kuria West", "Mabera", "Ntimaru", "Rongo", "Suna East", "Suna West", "Uriri"],
  "Mombasa": ["Changamwe", "Jomvu", "Kisauni", "Likoni", "Mvita", "Nyali"],
  "Murang'a": ["Gatanga", "Kahuro", "Kandara", "Kangema", "Kigumo", "Kiharu", "Mathioya", "Murang\u2019a South"],
  "Nairobi": ["Dagoretti North", "Dagoretti South", "Embakasi Central", "Embakasi East", "Embakasi North", "Embakasi South", "Embakasi West", "Kamukunji", "Kasarani", "Kibra", "Lang'ata", "Makadara", "Mathare", "Roysambu", "Ruaraka", "Starehe", "Westlands"],
  "Nakuru": ["Bahati", "Gilgil", "Kuresoi North", "Kuresoi South", "Molo", "Naivasha", "Nakuru Town East", "Nakuru Town West", "Njoro", "Rongai", "Subukia"],
  "Nandi": ["Aldai", "Chesumei", "Emgwen", "Mosop", "Namdi Hills", "Tindiret"],
  "Narok": ["Narok East", "Narok North", "Narok South", "Narok West", "Transmara East", "Transmara West"],
  "Nyamira": ["Borabu", "Manga", "Masaba North", "Nyamira North", "Nyamira South"],
  "Nyandarua": ["Kinangop", "Kipipiri", "Ndaragwa", "Ol Joro Orok", "Ol Kalou"],
  "Nyeri": ["Kieni East", "Kieni West", "Mathira East", "Mathira West", "Mkurweni", "Nyeri Town", "Othaya", "Tetu"],
  "Samburu": ["Samburu East", "Samburu North", "Samburu West"],
  "Siaya": ["Alego Usonga", "Bondo", "Gem", "Rarieda", "Ugenya", "Unguja"],
  "Taita-Taveta": ["Mwatate", "Taveta", "Voi", "Wundanyi"],
  "Tana River": ["Bura", "Galole", "Garsen"],
  "Tharaka-Nithi": ["Chuka", "Igambangobe", "Maara", "Muthambi", "Tharak North", "Tharaka South"],
  "Trans-Nzoia": ["Cherangany", "Endebess", "Kiminini", "Kwanza", "Saboti"],
  "Turkana": ["Loima", "Turkana Central", "Turkana East", "Turkana North", "Turkana South"],
  "Uasin Gishu": ["Ainabkoi", "Kapseret", "Kesses", "Moiben", "Soy", "Turbo"],
  "Vihiga": ["Emuhaya", "Hamisi", "Luanda", "Sabatia", "Vihiga"],
  "Wajir": ["Eldas", "Tarbaj", "Wajir East", "Wajir North", "Wajir South", "Wajir West"],
  "West Pokot": ["Central Pokot", "North Pokot", "Pokot South", "West Pokot"],
};

export const KENYA_COUNTIES = Object.keys(KENYA_COUNTY_SUBCOUNTIES).sort();