// Source: alvinchesaro/Kenya-Counties-SubCounties-and-Wards (CC0), cross-matched
// against our canonical county/sub-county list (kenya-subcounties.ts).
//
// IMPORTANT — coverage is PARTIAL, not authoritative:
//  - Nairobi, Bomet, and Kericho have no ward data in the source at all.
//  - For other counties, this source uses a mix of administrative sub-county
//    and electoral constituency naming, which don't always agree with our
//    canonical sub-county list. Only pairs that matched with confidence are
//    included here (193 of 310 sub-counties, ~62%); everything else is
//    deliberately omitted rather than guessed at.
//  - The form falls back to a free-text ward input whenever a county/sub-county
//    combination has no entry here — see FarmLocationStep.tsx.
//
// For full, authoritative coverage, this would need replacing with IEBC's
// official ward boundary data or a curated KNBS source.
export const KENYA_WARDS: Record<string, string[]> = {
  "Baringo|Baringo Central": ["Ewale", "Kesumet", "Mugunga", "Mukurweini"],
  "Baringo|Baringo North": ["Bartabwa", "Kabarnet", "Kabartonjo", "Kamok", "Moiben"],
  "Baringo|Baringo South": ["Kiptoi", "Maram", "Ndoga", "Rongai"],
  "Baringo|Mogotio": ["Eldoret East", "Kampi Ya Samaki", "Kerio Valley", "Mogotio", "Salawa"],
  "Baringo|Tiaty": ["Chepyuk", "Kang'Irangero", "Kologir", "Mogotio", "Ndanya"],
  "Bungoma|Kabuchai": ["Kabuchai", "Kabuchai East", "Kabuchai North", "Kabuchai South", "Kabuchai West"],
  "Bungoma|Kanduyi": ["Kanduyi", "Kanduyi East", "Kanduyi North", "Kanduyi South", "Kanduyi West"],
  "Bungoma|Sirisia": ["Cheptais", "Lwandanyi", "Malakisi/South Kulisiru", "Namwela", "Sirisia"],
  "Bungoma|Webuye East": ["Webuye", "Webuye East", "Webuye North", "Webuye South", "Webuye West"],
  "Bungoma|Webuye West": ["Webuye Central", "Webuye East", "Webuye South", "Webuye Town", "Webuye West"],
  "Busia|Butula": ["Butula South", "Marachi Central", "Marachi North", "Marachi West", "Mulwanda"],
  "Busia|Funyula": ["Bukhayo Central", "Bukhayo East", "Bukhayo West", "Funyula Town", "Nambale"],
  "Busia|Teso North": ["Amukura Central", "Amukura East", "Amukura West", "Ang'Urai North", "Ang'Urai South", "Malaba"],
  "Busia|Teso South": ["Amukura Central", "Ang'Urai North", "Ang'Urai South", "Malaba"],
  "Elgeyo-Marakwet|Keiyo North": ["Kabarak", "Kamariny", "Kesot", "Tambach"],
  "Elgeyo-Marakwet|Keiyo South": ["Chepkorio", "Kaptarakwa", "Kerio", "Kiptuiya", "Motioli", "Tambach"],
  "Elgeyo-Marakwet|Marakwet East": ["Kapkagaon", "Koibos", "Tirap"],
  "Elgeyo-Marakwet|Marakwet West": ["Kamoi", "Londiani", "Moiben Kuserwo", "Moiben/Chesongech", "Sambaria"],
  "Embu|Manyatta": ["Gaturi South", "Kirimari", "Kithimu", "Mbeti North", "Nginda", "Ruguru/Ngandori"],
  "Embu|Mbeere North": ["Evurore", "Muminji", "Nthawa"],
  "Embu|Mbeere South": ["Kiambere", "Makima", "Mavuria", "Mbeti South", "Mwea"],
  "Embu|Runyenjes": ["Central Ward", "Gaturi North", "Kagaari North", "Kagaari South", "Kyeni North", "Kyeni South"],
  "Garissa|Fafi": ["Bura", "Dekaharia", "Fafi", "Jarajila", "Nanighi"],
  "Garissa|Ijara": ["Hulugho", "Ijara", "Masalani", "Sangailu"],
  "Homa Bay|Kasipul": ["Mbita", "Ndhiwa Town", "Rangwe", "Uriri"],
  "Homa Bay|Ndhiwa": ["Kabondo Kasipul", "Mbita", "Ndhiwa Town", "Uriri"],
  "Homa Bay|Rangwe": ["Homa Bay", "Mbita", "Ndhiwa Town", "Uriri"],
  "Kakamega|Butere": ["Butere", "Butere Central", "Butere North", "Butere South"],
  "Kakamega|Khwisero": ["Khwisero", "Khwisero Central", "Khwisero East", "Khwisero West"],
  "Kakamega|Lugari": ["Butali", "Chekalini", "Chekalini East", "Chekalini West", "Mukhonje"],
  "Kakamega|Lurambi": ["Butsotso South", "Likhomani", "Muranda", "Sheer", "Shirere"],
  "Kakamega|Navakholo": ["Butsotso Central", "Butsotso North", "Mukhonje", "Navakholo", "Shinyalu"],
  "Kiambu|Gatundu North": ["Chania", "Githobokoni", "Gituamba", "Mang'U"],
  "Kiambu|Gatundu South": ["Kiamwangi", "Kiganjo", "Ndarugu", "Ngenda"],
  "Kiambu|Githunguri": ["Githiga", "Githunguri", "Ikinu", "Komothai", "Ngewa"],
  "Kiambu|Juja": ["Juja", "Kalimoni", "Murera", "Theta", "Witeithie"],
  "Kiambu|Kabete": ["Gitaru", "Kabete", "Muguga", "Nyadhuna", "Uthiru"],
  "Kiambu|Kiambaa": ["Cianda", "Karuri", "Kihara", "Muchatha", "Ndenderu"],
  "Kiambu|Kiambu": ["Ndumberi", "Riabai", "Ting'Ang'A", "Township"],
  "Kiambu|Kikuyu": ["Karai", "Kikuyu", "Kinoo", "Nachu", "Sigona"],
  "Kiambu|Lari": ["Kamburu", "Kijabe", "Kinale", "Lari/Kirenga", "Nyanduma"],
  "Kiambu|Limuru": ["Bibirioni", "Limuru Central", "Limuru East", "Ndeiya", "Ngecha Tigoni"],
  "Kiambu|Ruiru": ["Biashara", "Gatongora", "Gitothua", "Kahawa Sukari", "Kahawa Wendani", "Kiuu", "Mwihoko", "Mwiki"],
  "Kiambu|Thika Town": ["Gatuanyaga", "Hospital", "Kamenu", "Ngoliba", "Township"],
  "Kilifi|Ganze": ["Bamba", "Ganze", "Jaribuni", "Sokoke"],
  "Kilifi|Kaloleni": ["Kaloleni", "Kayafungo", "Mariakani", "Mwanamwinga"],
  "Kilifi|Kilifi North": ["Dabaso", "Kibarani", "Matsangoni", "Mnarani", "Sokoni", "Tezo", "Watamu"],
  "Kilifi|Kilifi South": ["Chasimba", "Junju", "Mtepeni", "Mwarakaya", "Shimo La Tewa"],
  "Kilifi|Magarini": ["Adu", "Garashi", "Gongoni", "Magarini", "Marafa", "Sabaki"],
  "Kilifi|Malindi": ["Ganda", "Jilore", "Kakuyuni", "Malindi Town", "Shella"],
  "Kilifi|Rabai": ["Kambe/Ribe", "Mwawesa", "Rabai/Kisurutini", "Ruruma"],
  "Kirinyaga|Kirinyaga Central": ["Inoi", "Kanyekini", "Kerugoya", "Mutira"],
  "Kisii|Bobasi": ["Bosongo", "Keera", "Nyamira Central", "Nyamira Town", "Nyankoya"],
  "Kisii|Bomachoge Borabu": ["Borabu", "Bosongo", "Nyamira Central", "Nyamira East", "Nyankoya"],
  "Kisii|Bomachoge Chache": ["Kegati", "Kegogro", "Nyamira Central", "Nyankoya", "Siambele"],
  "Kisii|Bonchari": ["Keera", "Magwagwa", "Nyamira Town", "Siambele"],
  "Kisii|Kitutu Chache North": ["Birongo", "Etago", "Kemera", "Kitutu Central", "Magwagwa", "Nyatieko"],
  "Kisii|Kitutu Chache South": ["Kegati", "Mwabosire", "Nango", "Nyamarama", "Nyankoya", "Nyatieko"],
  "Kisii|Nyaribari Chache": ["Bobasi", "Keera", "Kegati", "Nyamira Town", "Ririga"],
  "Kisii|Nyaribari Masaba": ["Bobasi", "Bosongo", "Momweta", "Nyamira Central", "Nyamira Town"],
  "Kisii|South Mugirango": ["Magwagwa", "Nyambunga", "Nyamira East", "Nyamira Town", "Nyankoya"],
  "Kisumu|Kisumu Central": ["Homa Bay", "Kisumu Town", "Mbita", "Nyatike"],
  "Kisumu|Kisumu East": ["Homa Bay", "Kisumu Town", "Mbita", "Nyatike"],
  "Kisumu|Kisumu West": ["Homa Bay", "Kisumu Town", "Mbita", "Nyatike"],
  "Kisumu|Nyakach": ["Homa Bay", "Kisumu Town", "Mbita", "Nyatike"],
  "Kisumu|Nyando": ["Homa Bay", "Kisumu Town", "Mbita", "Nyatike"],
  "Kisumu|Seme": ["Homa Bay", "Kisumu Town", "Mbita", "Nyatike"],
  "Kitui|Kitui Central": ["Kyangwithya East", "Kyangwithya West", "Miambani", "Mulango", "Township"],
  "Kitui|Kitui West": ["Kauwi", "Kwa Mutonga/Kithumula", "Matinyani", "Mutonguni"],
  "Kitui|Mwingi Central": ["Central", "Kivou", "Mui", "Nguni", "Nuu", "Waita"],
  "Kwale|Kinango": ["Chengoni/Samburu", "Kasemeni", "Kinango", "Mackinnon Road", "Mwavumbo", "Ndavaya", "Puma"],
  "Kwale|Lungalunga": ["Dzombo", "Mwereni", "Pongwe/Kikoneni", "Vanga"],
  "Kwale|Msambweni": ["Gombato Bongwe", "Kinondo", "Ramisi", "Ukunda"],
  "Laikipia|Laikipia East": ["Lamuria", "Nanyuki", "Ngobit", "Thingithu"],
  "Laikipia|Laikipia North": ["Bunyore", "Kimanjo", "Ol'Ng'Arua", "Suguta Marmar", "Tigonyi"],
  "Laikipia|Laikipia West": ["Gatarakwa", "Ndiriri", "Ol-Moran", "Rumuruti"],
  "Lamu|Lamu East": ["Basuba", "Faza", "Kiunga"],
  "Lamu|Lamu West": ["Bahari", "Hindi", "Hongwe", "Mkomani", "Mkunumbi", "Shella", "Witu"],
  "Machakos|Kathiani": ["Kathiani Central", "Lower Kaewa/Kaani", "Mitaboni", "Upper Kaewa/Iveti"],
  "Machakos|Machakos Town": ["Kalama", "Kola", "Machakos Central", "Mua", "Mumbuni North", "Mutituni", "Muvuti/Kiima-Kimwe"],
  "Machakos|Masinga": ["Ekalakala", "Kivaa", "Masinga Central", "Muthesya", "Ndithini"],
  "Machakos|Matungulu": ["Kyeleni", "Matungulu East", "Matungulu North", "Matungulu West", "Tala"],
  "Machakos|Mavoko": ["Athi River", "Kinanie", "Muthwani", "Syokimau/Mulolongo"],
  "Machakos|Mwala": ["Kibauni", "Makutano/Mwala", "Masii", "Mbiuni", "Muthetheni", "Wamunyu"],
  "Machakos|Yatta": ["Ikombe", "Katangi", "Kithimani", "Matuu", "Ndalani"],
  "Makueni|Kaiti": ["Ilima", "Kee", "Kilungu", "Ukia"],
  "Makueni|Kibwezi East": ["Ivingoni/Nzambani", "Masongaleni", "Mtito Andei", "Thange"],
  "Makueni|Kilome": ["Kasikeu", "Kiima Kiu/Kalanzoni", "Mukaa"],
  "Makueni|Makueni": ["Kathonzweni", "Kitise/Kithuki", "Mavindini", "Mbitini", "Muvau/Kikuumini", "Nzaui/Kilili/Kalamba", "Wote"],
  "Makueni|Mbooni": ["Kalawa", "Kiteta/Kisau", "Kithungo/Kitundu", "Mbooni", "Tulimani", "Waia-Kako"],
  "Mandera|Banissa": ["Banissa", "Derkhale", "Guba", "Kiliwehiri", "Malkamari"],
  "Mandera|Lafey": ["Alango Gof", "Fino", "Lafey", "Sala", "Waranqara"],
  "Mandera|Mandera East": ["Arabia", "Khalalio", "Libehia", "Neboi", "Township"],
  "Mandera|Mandera North": ["Ashabito", "Guticha", "Morothile", "Rhamu", "Rhamu-Dimtu"],
  "Mandera|Mandera South": ["Elwak North", "Elwak South", "Kutulo", "Shimbir Fatuma", "Wargadud"],
  "Mandera|Mandera West": ["Dandu", "Gither", "Lagsure", "Takaba", "Takaba South"],
  "Marsabit|Laisamis": ["Kargi/South Horr", "Korr/Ngurunit", "Laisamis", "Logo Logo", "Loiyangalani"],
  "Marsabit|Moyale": ["Butiye", "Golbo", "Heillu/Manyatta", "Moyale Township", "Obbu", "Sololo", "Uran"],
  "Marsabit|Saku": ["Karare", "Marsabit Central", "Sagante/Jaldessa"],
  "Meru|Buuri": ["Kibirichia", "Kiirua/Naari", "Kisima", "Ruiri/Rwarera", "Timau"],
  "Meru|Igembe Central": ["Akirang'Ondu", "Athiru Ruujine", "Igembe East", "Kangeta", "Njia"],
  "Meru|Igembe North": ["Amwathi", "Antuambui", "Antubetwe Kiongo", "Naathu", "Ntunene"],
  "Meru|Igembe South": ["Akachiu", "Athiru Gaiti", "Kanuni", "Kiegoi/Antubochiu", "Maua"],
  "Meru|Tigania East": ["Karama", "Kiguchwa", "Mikinduri", "Muthara", "Thangatha"],
  "Meru|Tigania West": ["Akithii", "Athwana", "Kianjai", "Mbeu", "Nkomo"],
  "Migori|Awendo": ["Awendo Town", "Kamagambo", "Kanyamkago", "Uriri"],
  "Migori|Kuria East": ["Awendo Town", "Kamagambo", "Kuria East", "Nyatike"],
  "Migori|Kuria West": ["Awendo Town", "Migori", "Nyatike", "Uriri"],
  "Migori|Rongo": ["Awendo Town", "Kanyamkago", "Migori", "Uriri"],
  "Mombasa|Changamwe": ["Airport", "Chaani", "Changamwe", "Kipevu", "Port Reitz"],
  "Mombasa|Jomvu": ["Jomvu Kuu", "Mikindani", "Miritini"],
  "Mombasa|Kisauni": ["Bamburi", "Junda", "Magogoni", "Mjambere", "Mtopanga", "Mwakirunge", "Shanzu"],
  "Mombasa|Likoni": ["Bofu", "Likoni", "Mtongwe", "Shika Adabu", "Timbwani"],
  "Mombasa|Mvita": ["Majengo", "Mji Wa Kale/Makadara", "Shimanzi/Ganjoni", "Tononoka", "Tudor"],
  "Mombasa|Nyali": ["Frere Town", "Kadzandani", "Kongowea", "Mkomani", "Ziwa La Ng'Ombe"],
  "Murang'a|Gatanga": ["Gatanga", "Ithanga", "Kakuzi/Mitubiri", "Kariara", "Kihumbu-Ini", "Mugumo-Ini"],
  "Murang'a|Kandara": ["Gaichanjiru", "Ithiru", "Kagundu-Ini", "Muruka", "Ng'Araria", "Ruchu"],
  "Murang'a|Kangema": ["Kanyenya-Ini", "Muguru", "Rwathia"],
  "Murang'a|Kigumo": ["Kahumbu", "Kangari", "Kigumo", "Kinyona", "Muthithi"],
  "Murang'a|Kiharu": ["Gaturi", "Mbiri", "Mugoiri", "Murarandia", "Township", "Wangu"],
  "Murang'a|Mathioya": ["Gitugi", "Kamacharia", "Kiru"],
  "Nakuru|Bahati": ["Kabatini", "Lanet", "Lanet/Umbui", "Wanyororu"],
  "Nakuru|Gilgil": ["Gilgil", "Kikopey", "Mbunde", "Murinduko"],
  "Nakuru|Kuresoi North": ["Kampio", "Kipchui", "Kiptuiya", "Kongasis", "Ndathiru", "Saboti"],
  "Nakuru|Kuresoi South": ["Aror", "Kiambiu", "Morop", "Ndaragwa", "Tenges"],
  "Nakuru|Molo": ["Koyumot", "Mariashon", "Molo", "Talai", "Teret"],
  "Nakuru|Naivasha": ["Hell'S Gate", "Humor", "Karagita", "Karati", "Maai Mahiu", "Viwandani"],
  "Nakuru|Nakuru Town East": ["Burnt Forest", "Gitombo", "Nakuru Town", "Subukia"],
  "Nakuru|Nakuru Town West": ["Naivasha", "Rhino", "Rose Cottage", "Shaaba", "Shalom"],
  "Nakuru|Njoro": ["Kisiriri", "Lare", "Mau Narok", "Mugoiri", "Mwitoti", "Ndiwa"],
  "Nakuru|Rongai": ["Kabazi", "Mosop", "Sirikwa", "Solai", "Suchai"],
  "Nakuru|Subukia": ["Gathing'A", "Subukia", "Waldai", "Wanyororu"],
  "Nandi|Aldai": ["Chemalal", "Kapchorwa", "Kapsaos", "Kipkoim"],
  "Nandi|Chesumei": ["Chebaru", "Kapsengere", "Kipworom", "Lelem", "Mugunga"],
  "Nandi|Emgwen": ["Kapngetuny", "Kipchepton", "Kiplombe"],
  "Nandi|Mosop": ["Kapsabet", "Kaptarakwa", "Kesumet", "Kipkabur", "Kiptuiya"],
  "Narok|Narok East": ["Kewapaki", "Naibor", "Olelo Sokwan", "Olesoswa", "Pambo"],
  "Narok|Narok North": ["Kipkelion", "Koyumot", "Motok", "Narok Town", "Olelshwa", "Suswa"],
  "Narok|Narok South": ["Eor Esiam", "Loita", "Majibu", "Mbirikani"],
  "Narok|Narok West": ["Inkarakapot", "Kimintet", "Mara", "Olakewua"],
  "Narok|Transmara East": ["Kebelio", "Keyian", "Migori", "Nyagawa"],
  "Narok|Transmara West": ["Kapsiru", "Kipkelion", "Moita"],
  "Nyamira|Borabu": ["Bokimonge", "Bomwagamo", "Machoge Chache", "Nyansiongo", "Rigoma"],
  "Nyandarua|Kinangop": ["Engineer", "Gathara", "Githabai", "Magumu", "Murungaru", "Njabini\\Kiburu", "North Kinangop", "Nyakio"],
  "Nyandarua|Kipipiri": ["Geta", "Githioro", "Kipipiri", "Wanjohi"],
  "Nyandarua|Ndaragwa": ["Central", "Kiriita", "Leshau/Pondo", "Shamata"],
  "Nyandarua|Ol Kalou": ["Kaimbaga", "Kanjuiri Range", "Karau", "Mirangine", "Rurii"],
  "Nyeri|Nyeri Town": ["Gatitu/Muruguru", "Kamakwa/Mukaro", "Kiganjo/Mathari", "Ruring'U", "Rware"],
  "Nyeri|Othaya": ["Chinga", "Iria-Ini", "Karima", "Mahiga"],
  "Nyeri|Tetu": ["Aguthi-Gaaki", "Dedan Kimanthi", "Wamagana"],
  "Samburu|Samburu East": ["Wamba East", "Wamba North", "Wamba West", "Waso"],
  "Samburu|Samburu North": ["Elbarta", "Nachola", "Ndoto", "Nyiro"],
  "Samburu|Samburu West": ["Lodokejek", "Loosuk", "Maralal", "Poro", "Suguta Marmar"],
  "Siaya|Alego Usonga": ["Mbita", "Nyakach", "Ugunja Town", "Uriri"],
  "Siaya|Bondo": ["Mbita", "Nyakach", "Ugunja Town", "Uriri"],
  "Siaya|Gem": ["Mbita", "Nyakach", "Ugunja Town", "Uriri"],
  "Siaya|Rarieda": ["Mbita", "Nyakach", "Ugunja Town", "Uriri"],
  "Siaya|Ugenya": ["Mbita", "Nyakach", "Ugenya Town", "Uriri"],
  "Taita-Taveta|Mwatate": ["Bura", "Chawia", "Mwatate", "Rong'E", "Wusi/Kishamba"],
  "Taita-Taveta|Taveta": ["Bomani", "Chala", "Mahoo", "Mata", "Mboghoni"],
  "Taita-Taveta|Voi": ["Kaloleni", "Kasigau", "Marungu", "Mbololo", "Ngolia", "Sagalla"],
  "Taita-Taveta|Wundanyi": ["Mwanda/Mgange", "Werugha", "Wumingu/Kishushe", "Wundanyi/Mbale"],
  "Tana River|Bura": ["Bangale", "Chewele", "Hirimani", "Madogo", "Sala"],
  "Tana River|Galole": ["Chewani", "Kinakomba", "Mikinduni", "Wayu"],
  "Tana River|Garsen": ["Garsen Central", "Garsen North", "Garsen South", "Garsen West", "Kipini East", "Kipini West"],
  "Tharaka-Nithi|Maara": ["Chogoria", "Ganga", "Mitheru", "Muthambi", "Mwimbi"],
  "Trans-Nzoia|Cherangany": ["Cherangany/Suwerwa", "Moi'S Bridge", "Muserechi", "Mwea", "Siuna"],
  "Trans-Nzoia|Kiminini": ["Kiminini", "Matunda", "Nalondo", "Sinyerere", "Waitaluk"],
  "Trans-Nzoia|Kwanza": ["Biketi", "Kapomboi", "Keiyo", "Kwanza"],
  "Trans-Nzoia|Saboti": ["Kiminini", "Machinjir", "Murundi", "Mwatate", "Saboti"],
  "Turkana|Loima": ["Kerio Delta", "Kotaruk/Lorengai", "Loima", "Lokiriama/Lorengai"],
  "Turkana|Turkana Central": ["Kanamkemer", "Kang'Atotha", "Lodwar Township"],
  "Turkana|Turkana East": ["Kapedo/Napeitom", "Kolobia"],
  "Turkana|Turkana North": ["Kaaleng/Kaikor", "Kaeris", "Kibish", "Lake Zone", "Lapur", "Nakalale"],
  "Turkana|Turkana South": ["Kalapata", "Katilu", "Lokichar"],
  "Uasin Gishu|Ainabkoi": ["Ainabkoi/Olare", "Kapsoya", "Kipsomba"],
  "Uasin Gishu|Kapseret": ["Kapsao", "Kapturo", "Kuinet/Kapsuswa", "Tarakwa"],
  "Uasin Gishu|Kesses": ["Chekaria", "Cheptil", "Kaptel/Kiptullo", "Tumeyo"],
  "Uasin Gishu|Moiben": ["Kapngetuny", "Kimumu", "Sergoit", "Tarakwa"],
  "Uasin Gishu|Soy": ["Kipsomba", "Koiwa", "Segero/Barsombe", "Soy", "Ziwa"],
  "Uasin Gishu|Turbo": ["Kamariny", "Kapseret", "Kipkaren", "Kiplombe", "Megun", "Naiberi"],
  "Vihiga|Emuhaya": ["Central Bunyore", "East Bunyore", "North Bunyore", "South Bunyore"],
  "Vihiga|Hamisi": ["Hamisi", "Hamisi East", "Hamisi North", "Hamisi South", "Hamisi West"],
  "Vihiga|Luanda": ["East Bunyore", "Emuhaya", "Luanda Town", "South Bunyore", "West Bunyore"],
  "Vihiga|Sabatia": ["Sabatia", "Sabatia East", "Sabatia North", "Sabatia South", "Sabatia West"],
  "Vihiga|Vihiga": ["Vihiga East", "Vihiga North", "Vihiga South", "Vihiga Town"],
  "Wajir|Eldas": ["Della", "Eldas", "Elnur/Tula Tula", "Lakoley South/Basir"],
  "Wajir|Tarbaj": ["Elben", "Sarman", "Tarbaj", "Wargadud"],
  "Wajir|Wajir East": ["Barwago", "Khorof/Harar", "Township", "Wagberi"],
  "Wajir|Wajir North": ["Batalu", "Bute", "Danaba", "Godoma", "Gurar", "Korondile", "Malkagufu"],
  "Wajir|Wajir South": ["Benane", "Burder", "Dadaja Bulla", "Diif", "Habasswein", "Ibrahim Ure", "Lagboghol South"],
  "Wajir|Wajir West": ["Adamasajide", "Arbajahan", "Ganyure/Wagalla", "Hadado/Athibohol"],
  "West Pokot|Pokot South": ["Batei", "Chepkorio", "Lombeh"],
};

/** Looks up wards for a county/sub-county pair. Returns null if not covered. */
export function getWards(county: string, subCounty: string): string[] | null {
  return KENYA_WARDS[`${county}|${subCounty}`] ?? null;
}